"""
DO NOT EDIT THIS FILE, unless you really know what you are doing...

This file is automatically generated by generate_mapping.py. To make
changes to this file, do so by re-running that code on the
appropriate directories in the Rayleigh source code.

There are three dictionaries defined here:

    INCITE_name_given_code  --- key is integer quantity code, value is string name
    INCITE_code_given_name  --- key is string name, value is integer quantity code
    INCITE_tex_given_code   --- key is integer quantity code, value is string LaTeX

"""
from collections import OrderedDict

INCITE_name_given_code = OrderedDict()
INCITE_code_given_name = OrderedDict()
INCITE_tex_given_code  = OrderedDict()

INCITE_name_given_code[1] = "v_r"
INCITE_code_given_name["v_r"] = 1
INCITE_tex_given_code[1] = "full"

INCITE_name_given_code[2] = "v_theta"
INCITE_code_given_name["v_theta"] = 2
INCITE_tex_given_code[2] = ""

INCITE_name_given_code[3] = "v_phi"
INCITE_code_given_name["v_phi"] = 3
INCITE_tex_given_code[3] = ""

INCITE_name_given_code[4] = "vp_r"
INCITE_code_given_name["vp_r"] = 4
INCITE_tex_given_code[4] = "fluctuating"

INCITE_name_given_code[5] = "vp_theta"
INCITE_code_given_name["vp_theta"] = 5
INCITE_tex_given_code[5] = ""

INCITE_name_given_code[6] = "vp_phi"
INCITE_code_given_name["vp_phi"] = 6
INCITE_tex_given_code[6] = ""

INCITE_name_given_code[7] = "vm_r"
INCITE_code_given_name["vm_r"] = 7
INCITE_tex_given_code[7] = "mean"

INCITE_name_given_code[8] = "vm_theta"
INCITE_code_given_name["vm_theta"] = 8
INCITE_tex_given_code[8] = ""

INCITE_name_given_code[9] = "vm_phi"
INCITE_code_given_name["vm_phi"] = 9
INCITE_tex_given_code[9] = ""

INCITE_name_given_code[10] = "dv_r_dr"
INCITE_code_given_name["dv_r_dr"] = 10
INCITE_tex_given_code[10] = "full"

INCITE_name_given_code[11] = "dv_theta_dr"
INCITE_code_given_name["dv_theta_dr"] = 11
INCITE_tex_given_code[11] = ""

INCITE_name_given_code[12] = "dv_phi_dr"
INCITE_code_given_name["dv_phi_dr"] = 12
INCITE_tex_given_code[12] = ""

INCITE_name_given_code[13] = "dvp_r_dr"
INCITE_code_given_name["dvp_r_dr"] = 13
INCITE_tex_given_code[13] = "fluctuating"

INCITE_name_given_code[14] = "dvp_theta_dr"
INCITE_code_given_name["dvp_theta_dr"] = 14
INCITE_tex_given_code[14] = ""

INCITE_name_given_code[15] = "dvp_phi_dr"
INCITE_code_given_name["dvp_phi_dr"] = 15
INCITE_tex_given_code[15] = ""

INCITE_name_given_code[16] = "dvm_r_dr"
INCITE_code_given_name["dvm_r_dr"] = 16
INCITE_tex_given_code[16] = "mean"

INCITE_name_given_code[17] = "dvm_theta_dr"
INCITE_code_given_name["dvm_theta_dr"] = 17
INCITE_tex_given_code[17] = ""

INCITE_name_given_code[18] = "dvm_phi_dr"
INCITE_code_given_name["dvm_phi_dr"] = 18
INCITE_tex_given_code[18] = ""

INCITE_name_given_code[19] = "dv_r_dt"
INCITE_code_given_name["dv_r_dt"] = 19
INCITE_tex_given_code[19] = "full"

INCITE_name_given_code[20] = "dv_theta_dt"
INCITE_code_given_name["dv_theta_dt"] = 20
INCITE_tex_given_code[20] = ""

INCITE_name_given_code[21] = "dv_phi_dt"
INCITE_code_given_name["dv_phi_dt"] = 21
INCITE_tex_given_code[21] = ""

INCITE_name_given_code[22] = "dvp_r_dt"
INCITE_code_given_name["dvp_r_dt"] = 22
INCITE_tex_given_code[22] = "fluctuating"

INCITE_name_given_code[23] = "dvp_theta_dt"
INCITE_code_given_name["dvp_theta_dt"] = 23
INCITE_tex_given_code[23] = ""

INCITE_name_given_code[24] = "dvp_phi_dt"
INCITE_code_given_name["dvp_phi_dt"] = 24
INCITE_tex_given_code[24] = ""

INCITE_name_given_code[25] = "dvm_r_dt"
INCITE_code_given_name["dvm_r_dt"] = 25
INCITE_tex_given_code[25] = "mean"

INCITE_name_given_code[26] = "dvm_theta_dt"
INCITE_code_given_name["dvm_theta_dt"] = 26
INCITE_tex_given_code[26] = ""

INCITE_name_given_code[27] = "dvm_phi_dt"
INCITE_code_given_name["dvm_phi_dt"] = 27
INCITE_tex_given_code[27] = ""

INCITE_name_given_code[28] = "dv_r_dp"
INCITE_code_given_name["dv_r_dp"] = 28
INCITE_tex_given_code[28] = "full"

INCITE_name_given_code[29] = "dv_theta_dp"
INCITE_code_given_name["dv_theta_dp"] = 29
INCITE_tex_given_code[29] = ""

INCITE_name_given_code[30] = "dv_phi_dp"
INCITE_code_given_name["dv_phi_dp"] = 30
INCITE_tex_given_code[30] = ""

INCITE_name_given_code[31] = "dvp_r_dp"
INCITE_code_given_name["dvp_r_dp"] = 31
INCITE_tex_given_code[31] = "fluctuating"

INCITE_name_given_code[32] = "dvp_theta_dp"
INCITE_code_given_name["dvp_theta_dp"] = 32
INCITE_tex_given_code[32] = "(same as full if"

INCITE_name_given_code[33] = "dvp_phi_dp"
INCITE_code_given_name["dvp_phi_dp"] = 33
INCITE_tex_given_code[33] = "mean is azimuthal)"

INCITE_name_given_code[34] = "dvm_r_dp"
INCITE_code_given_name["dvm_r_dp"] = 34
INCITE_tex_given_code[34] = "we keep the phi derivatives of the mean"

INCITE_name_given_code[35] = "dvm_theta_dp"
INCITE_code_given_name["dvm_theta_dp"] = 35
INCITE_tex_given_code[35] = "here, even though they are zero."

INCITE_name_given_code[36] = "dvm_phi_dp"
INCITE_code_given_name["dvm_phi_dp"] = 36
INCITE_tex_given_code[36] = "somewhat useful placeholders..."

INCITE_name_given_code[37] = "dv_r_dtr"
INCITE_code_given_name["dv_r_dtr"] = 37
INCITE_tex_given_code[37] = "full"

INCITE_name_given_code[38] = "dv_theta_dtr"
INCITE_code_given_name["dv_theta_dtr"] = 38
INCITE_tex_given_code[38] = ""

INCITE_name_given_code[39] = "dv_phi_dtr"
INCITE_code_given_name["dv_phi_dtr"] = 39
INCITE_tex_given_code[39] = ""

INCITE_name_given_code[40] = "dvp_r_dtr"
INCITE_code_given_name["dvp_r_dtr"] = 40
INCITE_tex_given_code[40] = "fluctuating"

INCITE_name_given_code[41] = "dvp_theta_dtr"
INCITE_code_given_name["dvp_theta_dtr"] = 41
INCITE_tex_given_code[41] = ""

INCITE_name_given_code[42] = "dvp_phi_dtr"
INCITE_code_given_name["dvp_phi_dtr"] = 42
INCITE_tex_given_code[42] = ""

INCITE_name_given_code[43] = "dvm_r_dtr"
INCITE_code_given_name["dvm_r_dtr"] = 43
INCITE_tex_given_code[43] = "mean"

INCITE_name_given_code[44] = "dvm_theta_dtr"
INCITE_code_given_name["dvm_theta_dtr"] = 44
INCITE_tex_given_code[44] = ""

INCITE_name_given_code[45] = "dvm_phi_dtr"
INCITE_code_given_name["dvm_phi_dtr"] = 45
INCITE_tex_given_code[45] = ""

INCITE_name_given_code[46] = "dv_r_dprs"
INCITE_code_given_name["dv_r_dprs"] = 46
INCITE_tex_given_code[46] = "full"

INCITE_name_given_code[47] = "dv_theta_dprs"
INCITE_code_given_name["dv_theta_dprs"] = 47
INCITE_tex_given_code[47] = ""

INCITE_name_given_code[48] = "dv_phi_dprs"
INCITE_code_given_name["dv_phi_dprs"] = 48
INCITE_tex_given_code[48] = ""

INCITE_name_given_code[49] = "dvp_r_dprs"
INCITE_code_given_name["dvp_r_dprs"] = 49
INCITE_tex_given_code[49] = "fluctuating"

INCITE_name_given_code[50] = "dvp_theta_dprs"
INCITE_code_given_name["dvp_theta_dprs"] = 50
INCITE_tex_given_code[50] = ""

INCITE_name_given_code[51] = "dvp_phi_dprs"
INCITE_code_given_name["dvp_phi_dprs"] = 51
INCITE_tex_given_code[51] = ""

INCITE_name_given_code[52] = "dvm_r_dprs"
INCITE_code_given_name["dvm_r_dprs"] = 52
INCITE_tex_given_code[52] = "mean"

INCITE_name_given_code[53] = "dvm_theta_dprs"
INCITE_code_given_name["dvm_theta_dprs"] = 53
INCITE_tex_given_code[53] = ""

INCITE_name_given_code[54] = "dvm_phi_dprs"
INCITE_code_given_name["dvm_phi_dprs"] = 54
INCITE_tex_given_code[54] = ""

INCITE_name_given_code[55] = "rhov_r"
INCITE_code_given_name["rhov_r"] = 55
INCITE_tex_given_code[55] = "full"

INCITE_name_given_code[56] = "rhov_theta"
INCITE_code_given_name["rhov_theta"] = 56
INCITE_tex_given_code[56] = ""

INCITE_name_given_code[57] = "rhov_phi"
INCITE_code_given_name["rhov_phi"] = 57
INCITE_tex_given_code[57] = ""

INCITE_name_given_code[58] = "rhovp_r"
INCITE_code_given_name["rhovp_r"] = 58
INCITE_tex_given_code[58] = "fluctuating"

INCITE_name_given_code[59] = "rhovp_theta"
INCITE_code_given_name["rhovp_theta"] = 59
INCITE_tex_given_code[59] = ""

INCITE_name_given_code[60] = "rhovp_phi"
INCITE_code_given_name["rhovp_phi"] = 60
INCITE_tex_given_code[60] = ""

INCITE_name_given_code[61] = "rhovm_r"
INCITE_code_given_name["rhovm_r"] = 61
INCITE_tex_given_code[61] = "mean"

INCITE_name_given_code[62] = "rhovm_theta"
INCITE_code_given_name["rhovm_theta"] = 62
INCITE_tex_given_code[62] = ""

INCITE_name_given_code[63] = "rhovm_phi"
INCITE_code_given_name["rhovm_phi"] = 63
INCITE_tex_given_code[63] = ""

INCITE_name_given_code[64] = "entropy"
INCITE_code_given_name["entropy"] = 64
INCITE_tex_given_code[64] = "full"

INCITE_name_given_code[65] = "pressure"
INCITE_code_given_name["pressure"] = 65
INCITE_tex_given_code[65] = ""

INCITE_name_given_code[66] = "entropy_p"
INCITE_code_given_name["entropy_p"] = 66
INCITE_tex_given_code[66] = "fluctuating"

INCITE_name_given_code[67] = "pressure_p"
INCITE_code_given_name["pressure_p"] = 67
INCITE_tex_given_code[67] = ""

INCITE_name_given_code[68] = "entropy_m"
INCITE_code_given_name["entropy_m"] = 68
INCITE_tex_given_code[68] = "mean"

INCITE_name_given_code[69] = "pressure_m"
INCITE_code_given_name["pressure_m"] = 69
INCITE_tex_given_code[69] = ""

INCITE_name_given_code[70] = "entropy_dr"
INCITE_code_given_name["entropy_dr"] = 70
INCITE_tex_given_code[70] = "full"

INCITE_name_given_code[71] = "pressure_dr"
INCITE_code_given_name["pressure_dr"] = 71
INCITE_tex_given_code[71] = ""

INCITE_name_given_code[72] = "entropy_p_dr"
INCITE_code_given_name["entropy_p_dr"] = 72
INCITE_tex_given_code[72] = "fluctuating"

INCITE_name_given_code[73] = "pressure_p_dr"
INCITE_code_given_name["pressure_p_dr"] = 73
INCITE_tex_given_code[73] = ""

INCITE_name_given_code[74] = "entropy_m_dr"
INCITE_code_given_name["entropy_m_dr"] = 74
INCITE_tex_given_code[74] = "mean"

INCITE_name_given_code[75] = "pressure_m_dr"
INCITE_code_given_name["pressure_m_dr"] = 75
INCITE_tex_given_code[75] = ""

INCITE_name_given_code[76] = "entropy_dtheta"
INCITE_code_given_name["entropy_dtheta"] = 76
INCITE_tex_given_code[76] = "full"

INCITE_name_given_code[77] = "pressure_dtheta"
INCITE_code_given_name["pressure_dtheta"] = 77
INCITE_tex_given_code[77] = ""

INCITE_name_given_code[78] = "entropy_p_dtheta"
INCITE_code_given_name["entropy_p_dtheta"] = 78
INCITE_tex_given_code[78] = "fluctuating"

INCITE_name_given_code[79] = "pressure_p_dtheta"
INCITE_code_given_name["pressure_p_dtheta"] = 79
INCITE_tex_given_code[79] = ""

INCITE_name_given_code[80] = "entropy_m_dtheta"
INCITE_code_given_name["entropy_m_dtheta"] = 80
INCITE_tex_given_code[80] = "mean"

INCITE_name_given_code[81] = "pressure_m_dtheta"
INCITE_code_given_name["pressure_m_dtheta"] = 81
INCITE_tex_given_code[81] = ""

INCITE_name_given_code[82] = "entropy_dphi"
INCITE_code_given_name["entropy_dphi"] = 82
INCITE_tex_given_code[82] = "full"

INCITE_name_given_code[83] = "pressure_dphi"
INCITE_code_given_name["pressure_dphi"] = 83
INCITE_tex_given_code[83] = ""

INCITE_name_given_code[84] = "entropy_p_dphi"
INCITE_code_given_name["entropy_p_dphi"] = 84
INCITE_tex_given_code[84] = "fluctuating"

INCITE_name_given_code[85] = "pressure_p_dphi"
INCITE_code_given_name["pressure_p_dphi"] = 85
INCITE_tex_given_code[85] = ""

INCITE_name_given_code[86] = "entropy_m_dphi"
INCITE_code_given_name["entropy_m_dphi"] = 86
INCITE_tex_given_code[86] = "mean"

INCITE_name_given_code[87] = "pressure_m_dphi"
INCITE_code_given_name["pressure_m_dphi"] = 87
INCITE_tex_given_code[87] = ""

INCITE_name_given_code[88] = "entropy_dtr"
INCITE_code_given_name["entropy_dtr"] = 88
INCITE_tex_given_code[88] = "full"

INCITE_name_given_code[89] = "pressure_dtr"
INCITE_code_given_name["pressure_dtr"] = 89
INCITE_tex_given_code[89] = ""

INCITE_name_given_code[90] = "entropy_p_dtr"
INCITE_code_given_name["entropy_p_dtr"] = 90
INCITE_tex_given_code[90] = "fluctuating"

INCITE_name_given_code[91] = "pressure_p_dtr"
INCITE_code_given_name["pressure_p_dtr"] = 91
INCITE_tex_given_code[91] = ""

INCITE_name_given_code[92] = "entropy_m_dtr"
INCITE_code_given_name["entropy_m_dtr"] = 92
INCITE_tex_given_code[92] = "mean"

INCITE_name_given_code[93] = "pressure_m_dtr"
INCITE_code_given_name["pressure_m_dtr"] = 93
INCITE_tex_given_code[93] = ""

INCITE_name_given_code[94] = "entropy_dprs"
INCITE_code_given_name["entropy_dprs"] = 94
INCITE_tex_given_code[94] = "full"

INCITE_name_given_code[95] = "pressure_dprs"
INCITE_code_given_name["pressure_dprs"] = 95
INCITE_tex_given_code[95] = ""

INCITE_name_given_code[96] = "entropy_p_dprs"
INCITE_code_given_name["entropy_p_dprs"] = 96
INCITE_tex_given_code[96] = "fluctuating"

INCITE_name_given_code[97] = "pressure_p_dprs"
INCITE_code_given_name["pressure_p_dprs"] = 97
INCITE_tex_given_code[97] = ""

INCITE_name_given_code[98] = "entropy_m_dprs"
INCITE_code_given_name["entropy_m_dprs"] = 98
INCITE_tex_given_code[98] = "mean"

INCITE_name_given_code[99] = "pressure_m_dprs"
INCITE_code_given_name["pressure_m_dprs"] = 99
INCITE_tex_given_code[99] = ""

INCITE_name_given_code[100] = "rhopressure_dr"
INCITE_code_given_name["rhopressure_dr"] = 100
INCITE_tex_given_code[100] = ""

INCITE_name_given_code[101] = "rhopressurep_dr"
INCITE_code_given_name["rhopressurep_dr"] = 101
INCITE_tex_given_code[101] = ""

INCITE_name_given_code[102] = "rhopressurem_dr"
INCITE_code_given_name["rhopressurem_dr"] = 102
INCITE_tex_given_code[102] = ""

INCITE_name_given_code[103] = "vort_r"
INCITE_code_given_name["vort_r"] = 103
INCITE_tex_given_code[103] = "full"

INCITE_name_given_code[104] = "vort_theta"
INCITE_code_given_name["vort_theta"] = 104
INCITE_tex_given_code[104] = ""

INCITE_name_given_code[105] = "vort_phi"
INCITE_code_given_name["vort_phi"] = 105
INCITE_tex_given_code[105] = ""

INCITE_name_given_code[106] = "vortp_r"
INCITE_code_given_name["vortp_r"] = 106
INCITE_tex_given_code[106] = "fluctuating"

INCITE_name_given_code[107] = "vortp_theta"
INCITE_code_given_name["vortp_theta"] = 107
INCITE_tex_given_code[107] = ""

INCITE_name_given_code[108] = "vortp_phi"
INCITE_code_given_name["vortp_phi"] = 108
INCITE_tex_given_code[108] = ""

INCITE_name_given_code[109] = "vortm_r"
INCITE_code_given_name["vortm_r"] = 109
INCITE_tex_given_code[109] = "mean"

INCITE_name_given_code[110] = "vortm_theta"
INCITE_code_given_name["vortm_theta"] = 110
INCITE_tex_given_code[110] = ""

INCITE_name_given_code[111] = "vortm_phi"
INCITE_code_given_name["vortm_phi"] = 111
INCITE_tex_given_code[111] = ""

INCITE_name_given_code[112] = "enstrophy"
INCITE_code_given_name["enstrophy"] = 112
INCITE_tex_given_code[112] = "enstrophy"

INCITE_name_given_code[113] = "enstrophy_pm"
INCITE_code_given_name["enstrophy_pm"] = 113
INCITE_tex_given_code[113] = "(fluctuating-mean)"

INCITE_name_given_code[114] = "enstrophy_mm"
INCITE_code_given_name["enstrophy_mm"] = 114
INCITE_tex_given_code[114] = "(mean-mean)"

INCITE_name_given_code[115] = "enstrophy_pp"
INCITE_code_given_name["enstrophy_pp"] = 115
INCITE_tex_given_code[115] = "(fluct-fluct)"

INCITE_name_given_code[116] = "ecrossb_r"
INCITE_code_given_name["ecrossb_r"] = 116
INCITE_tex_given_code[116] = "[exb]_r (un-normalized poynting flux)"

INCITE_name_given_code[117] = "ke_flux_radial"
INCITE_code_given_name["ke_flux_radial"] = 117
INCITE_tex_given_code[117] = "vr*ke"

INCITE_name_given_code[118] = "thermale_flux_radial"
INCITE_code_given_name["thermale_flux_radial"] = 118
INCITE_tex_given_code[118] = "vr*rho_bar*t_bar*s or vr*t"

INCITE_name_given_code[119] = "enth_flux_radial"
INCITE_code_given_name["enth_flux_radial"] = 119
INCITE_tex_given_code[119] = "vr*cp*rho_bar*t"

INCITE_name_given_code[120] = "visc_flux_r"
INCITE_code_given_name["visc_flux_r"] = 120
INCITE_tex_given_code[120] = "-[div dot d]_r"

INCITE_name_given_code[121] = "vol_heat_flux"
INCITE_code_given_name["vol_heat_flux"] = 121
INCITE_tex_given_code[121] = "flux associated with volumetric heating"

INCITE_name_given_code[122] = "cond_flux_r"
INCITE_code_given_name["cond_flux_r"] = 122
INCITE_tex_given_code[122] = "thermal conductive flux"

INCITE_name_given_code[123] = "vol_heating"
INCITE_code_given_name["vol_heating"] = 123
INCITE_tex_given_code[123] = "volumetric heating function"

INCITE_name_given_code[124] = "visc_heating"
INCITE_code_given_name["visc_heating"] = 124
INCITE_tex_given_code[124] = "viscous heating"

INCITE_name_given_code[125] = "kinetic_energy"
INCITE_code_given_name["kinetic_energy"] = 125
INCITE_tex_given_code[125] = "1/2 rho_bar v^2"

INCITE_name_given_code[126] = "radial_ke"
INCITE_code_given_name["radial_ke"] = 126
INCITE_tex_given_code[126] = "1/2 rho_bar {v_r}^2"

INCITE_name_given_code[127] = "theta_ke"
INCITE_code_given_name["theta_ke"] = 127
INCITE_tex_given_code[127] = "1/2 rho_bar {v_theta}^2"

INCITE_name_given_code[128] = "phi_ke"
INCITE_code_given_name["phi_ke"] = 128
INCITE_tex_given_code[128] = "1/2 rho_bar {v_phi}^2"

INCITE_name_given_code[129] = "mkinetic_energy"
INCITE_code_given_name["mkinetic_energy"] = 129
INCITE_tex_given_code[129] = "1/2 rho_bar <v>^2"

INCITE_name_given_code[130] = "radial_mke"
INCITE_code_given_name["radial_mke"] = 130
INCITE_tex_given_code[130] = "1/2 rho_bar <v_r>^2"

INCITE_name_given_code[131] = "theta_mke"
INCITE_code_given_name["theta_mke"] = 131
INCITE_tex_given_code[131] = "1/2 rho_bar <v_theta>^2"

INCITE_name_given_code[132] = "phi_mke"
INCITE_code_given_name["phi_mke"] = 132
INCITE_tex_given_code[132] = "1/2 rho_bar <v_phi>^2"

INCITE_name_given_code[133] = "pkinetic_energy"
INCITE_code_given_name["pkinetic_energy"] = 133
INCITE_tex_given_code[133] = "1/2 rho_bar {v'}^2"

INCITE_name_given_code[134] = "radial_pke"
INCITE_code_given_name["radial_pke"] = 134
INCITE_tex_given_code[134] = "1/2 rho_bar {v_r'}^2"

INCITE_name_given_code[135] = "theta_pke"
INCITE_code_given_name["theta_pke"] = 135
INCITE_tex_given_code[135] = "1/2 rho_bar {v_theta'}^2"

INCITE_name_given_code[136] = "phi_pke"
INCITE_code_given_name["phi_pke"] = 136
INCITE_tex_given_code[136] = "1/2 rho_bar {v_phi'}^2"

INCITE_name_given_code[137] = "vsq"
INCITE_code_given_name["vsq"] = 137
INCITE_tex_given_code[137] = "v^2"

INCITE_name_given_code[138] = "radial_vsq"
INCITE_code_given_name["radial_vsq"] = 138
INCITE_tex_given_code[138] = "{v_r}^2"

INCITE_name_given_code[139] = "theta_vsq"
INCITE_code_given_name["theta_vsq"] = 139
INCITE_tex_given_code[139] = "{v_theta}^2"

INCITE_name_given_code[140] = "phi_vsq"
INCITE_code_given_name["phi_vsq"] = 140
INCITE_tex_given_code[140] = "{v_phi}^2"

INCITE_name_given_code[141] = "mvsq"
INCITE_code_given_name["mvsq"] = 141
INCITE_tex_given_code[141] = "<v>^2"

INCITE_name_given_code[142] = "radial_mvsq"
INCITE_code_given_name["radial_mvsq"] = 142
INCITE_tex_given_code[142] = "<v_r>^2"

INCITE_name_given_code[143] = "theta_mvsq"
INCITE_code_given_name["theta_mvsq"] = 143
INCITE_tex_given_code[143] = "<v_theta>^2"

INCITE_name_given_code[144] = "phi_mvsq"
INCITE_code_given_name["phi_mvsq"] = 144
INCITE_tex_given_code[144] = "<v_phi>^2"

INCITE_name_given_code[145] = "pvsq"
INCITE_code_given_name["pvsq"] = 145
INCITE_tex_given_code[145] = "{v'}^2"

INCITE_name_given_code[146] = "radial_pvsq"
INCITE_code_given_name["radial_pvsq"] = 146
INCITE_tex_given_code[146] = "{v_r'}^2"

INCITE_name_given_code[147] = "theta_pvsq"
INCITE_code_given_name["theta_pvsq"] = 147
INCITE_tex_given_code[147] = "{v_theta'}^2"

INCITE_name_given_code[148] = "phi_pvsq"
INCITE_code_given_name["phi_pvsq"] = 148
INCITE_tex_given_code[148] = "{v_phi'}^2"

INCITE_name_given_code[149] = "amom_fluct_r"
INCITE_code_given_name["amom_fluct_r"] = 149
INCITE_tex_given_code[149] = "rho_bar * r * sintheta * {v_r'} * {v_phi'}"

INCITE_name_given_code[150] = "amom_fluct_theta"
INCITE_code_given_name["amom_fluct_theta"] = 150
INCITE_tex_given_code[150] = "rho_bar * r * sintheta * {v_theta'} * {v_phi'}"

INCITE_name_given_code[151] = "amom_dr_r"
INCITE_code_given_name["amom_dr_r"] = 151
INCITE_tex_given_code[151] = "rho_bar * r * sintheta * <v_r> * <v_phi>"

INCITE_name_given_code[152] = "amom_dr_theta"
INCITE_code_given_name["amom_dr_theta"] = 152
INCITE_tex_given_code[152] = "rho_bar * r * sintheta * <v_theta> * <v_phi>"

INCITE_name_given_code[153] = "amom_mean_r"
INCITE_code_given_name["amom_mean_r"] = 153
INCITE_tex_given_code[153] = "rho_bar * r^2 * sintheta^2 * <v_r> * omega"

INCITE_name_given_code[154] = "amom_mean_theta"
INCITE_code_given_name["amom_mean_theta"] = 154
INCITE_tex_given_code[154] = "rho_bar * r^2 * sintheta^2 * <v_theta> * omega"

INCITE_name_given_code[155] = "v_grad_v_r"
INCITE_code_given_name["v_grad_v_r"] = 155
INCITE_tex_given_code[155] = "radial component of v dot grad v"

INCITE_name_given_code[156] = "v_grad_v_theta"
INCITE_code_given_name["v_grad_v_theta"] = 156
INCITE_tex_given_code[156] = "theta component of v dot grad v"

INCITE_name_given_code[157] = "v_grad_v_phi"
INCITE_code_given_name["v_grad_v_phi"] = 157
INCITE_tex_given_code[157] = "phi component of v dot grad v"

INCITE_name_given_code[158] = "vp_grad_vm_r"
INCITE_code_given_name["vp_grad_vm_r"] = 158
INCITE_tex_given_code[158] = "radial component of v' dot grad <v>"

INCITE_name_given_code[159] = "vp_grad_vm_theta"
INCITE_code_given_name["vp_grad_vm_theta"] = 159
INCITE_tex_given_code[159] = "theta component of v' dot grad <v>"

INCITE_name_given_code[160] = "vp_grad_vm_phi"
INCITE_code_given_name["vp_grad_vm_phi"] = 160
INCITE_tex_given_code[160] = "phi component of v' dot grad <v>"

INCITE_name_given_code[161] = "vm_grad_vp_r"
INCITE_code_given_name["vm_grad_vp_r"] = 161
INCITE_tex_given_code[161] = "radial component of <v> dot grad v'"

INCITE_name_given_code[162] = "vm_grad_vp_theta"
INCITE_code_given_name["vm_grad_vp_theta"] = 162
INCITE_tex_given_code[162] = "theta component of <v> dot grad v'"

INCITE_name_given_code[163] = "vm_grad_vp_phi"
INCITE_code_given_name["vm_grad_vp_phi"] = 163
INCITE_tex_given_code[163] = "phi component of <v> dot grad v'"

INCITE_name_given_code[164] = "vp_grad_vp_r"
INCITE_code_given_name["vp_grad_vp_r"] = 164
INCITE_tex_given_code[164] = "radial component of v' dot grad v'"

INCITE_name_given_code[165] = "vp_grad_vp_theta"
INCITE_code_given_name["vp_grad_vp_theta"] = 165
INCITE_tex_given_code[165] = "theta component of v' dot grad v'"

INCITE_name_given_code[166] = "vp_grad_vp_phi"
INCITE_code_given_name["vp_grad_vp_phi"] = 166
INCITE_tex_given_code[166] = "phi component of v' dot grad v'"

INCITE_name_given_code[167] = "vm_grad_vm_r"
INCITE_code_given_name["vm_grad_vm_r"] = 167
INCITE_tex_given_code[167] = "radial component of <v> dot grad <v>"

INCITE_name_given_code[168] = "vm_grad_vm_theta"
INCITE_code_given_name["vm_grad_vm_theta"] = 168
INCITE_tex_given_code[168] = "theta component of <v> dot grad <v>"

INCITE_name_given_code[169] = "vm_grad_vm_phi"
INCITE_code_given_name["vm_grad_vm_phi"] = 169
INCITE_tex_given_code[169] = "phi component of <v> dot grad <v>"

INCITE_name_given_code[170] = "buoyancy_force"
INCITE_code_given_name["buoyancy_force"] = 170
INCITE_tex_given_code[170] = ""

INCITE_name_given_code[171] = "buoyancy_pforce"
INCITE_code_given_name["buoyancy_pforce"] = 171
INCITE_tex_given_code[171] = ""

INCITE_name_given_code[172] = "buoyancy_mforce"
INCITE_code_given_name["buoyancy_mforce"] = 172
INCITE_tex_given_code[172] = ""

INCITE_name_given_code[173] = "coriolis_force_r"
INCITE_code_given_name["coriolis_force_r"] = 173
INCITE_tex_given_code[173] = ""

INCITE_name_given_code[174] = "coriolis_force_theta"
INCITE_code_given_name["coriolis_force_theta"] = 174
INCITE_tex_given_code[174] = ""

INCITE_name_given_code[175] = "coriolis_force_phi"
INCITE_code_given_name["coriolis_force_phi"] = 175
INCITE_tex_given_code[175] = ""

INCITE_name_given_code[176] = "coriolis_pforce_r"
INCITE_code_given_name["coriolis_pforce_r"] = 176
INCITE_tex_given_code[176] = ""

INCITE_name_given_code[177] = "coriolis_pforce_theta"
INCITE_code_given_name["coriolis_pforce_theta"] = 177
INCITE_tex_given_code[177] = ""

INCITE_name_given_code[178] = "coriolis_pforce_phi"
INCITE_code_given_name["coriolis_pforce_phi"] = 178
INCITE_tex_given_code[178] = ""

INCITE_name_given_code[179] = "coriolis_mforce_r"
INCITE_code_given_name["coriolis_mforce_r"] = 179
INCITE_tex_given_code[179] = ""

INCITE_name_given_code[180] = "coriolis_mforce_theta"
INCITE_code_given_name["coriolis_mforce_theta"] = 180
INCITE_tex_given_code[180] = ""

INCITE_name_given_code[181] = "coriolis_mforce_phi"
INCITE_code_given_name["coriolis_mforce_phi"] = 181
INCITE_tex_given_code[181] = ""

INCITE_name_given_code[182] = "viscous_force_r"
INCITE_code_given_name["viscous_force_r"] = 182
INCITE_tex_given_code[182] = ""

INCITE_name_given_code[183] = "viscous_force_theta"
INCITE_code_given_name["viscous_force_theta"] = 183
INCITE_tex_given_code[183] = ""

INCITE_name_given_code[184] = "viscous_force_phi"
INCITE_code_given_name["viscous_force_phi"] = 184
INCITE_tex_given_code[184] = ""

INCITE_name_given_code[185] = "viscous_pforce_r"
INCITE_code_given_name["viscous_pforce_r"] = 185
INCITE_tex_given_code[185] = ""

INCITE_name_given_code[186] = "viscous_pforce_theta"
INCITE_code_given_name["viscous_pforce_theta"] = 186
INCITE_tex_given_code[186] = ""

INCITE_name_given_code[187] = "viscous_pforce_phi"
INCITE_code_given_name["viscous_pforce_phi"] = 187
INCITE_tex_given_code[187] = ""

INCITE_name_given_code[188] = "viscous_mforce_r"
INCITE_code_given_name["viscous_mforce_r"] = 188
INCITE_tex_given_code[188] = ""

INCITE_name_given_code[189] = "viscous_mforce_theta"
INCITE_code_given_name["viscous_mforce_theta"] = 189
INCITE_tex_given_code[189] = ""

INCITE_name_given_code[190] = "viscous_mforce_phi"
INCITE_code_given_name["viscous_mforce_phi"] = 190
INCITE_tex_given_code[190] = ""

INCITE_name_given_code[191] = "diagnostic1"
INCITE_code_given_name["diagnostic1"] = 191
INCITE_tex_given_code[191] = ""

INCITE_name_given_code[192] = "diagnostic2"
INCITE_code_given_name["diagnostic2"] = 192
INCITE_tex_given_code[192] = ""

INCITE_name_given_code[193] = "test_y11"
INCITE_code_given_name["test_y11"] = 193
INCITE_tex_given_code[193] = ""

INCITE_name_given_code[194] = "test_y22"
INCITE_code_given_name["test_y22"] = 194
INCITE_tex_given_code[194] = ""

INCITE_name_given_code[195] = "test_y22_sq"
INCITE_code_given_name["test_y22_sq"] = 195
INCITE_tex_given_code[195] = ""

INCITE_name_given_code[401] = "b_r"
INCITE_code_given_name["b_r"] = 401
INCITE_tex_given_code[401] = "full"

INCITE_name_given_code[402] = "b_theta"
INCITE_code_given_name["b_theta"] = 402
INCITE_tex_given_code[402] = ""

INCITE_name_given_code[403] = "b_phi"
INCITE_code_given_name["b_phi"] = 403
INCITE_tex_given_code[403] = ""

INCITE_name_given_code[404] = "bp_r"
INCITE_code_given_name["bp_r"] = 404
INCITE_tex_given_code[404] = "fluctuating"

INCITE_name_given_code[405] = "bp_theta"
INCITE_code_given_name["bp_theta"] = 405
INCITE_tex_given_code[405] = ""

INCITE_name_given_code[406] = "bp_phi"
INCITE_code_given_name["bp_phi"] = 406
INCITE_tex_given_code[406] = ""

INCITE_name_given_code[407] = "bm_r"
INCITE_code_given_name["bm_r"] = 407
INCITE_tex_given_code[407] = "mean"

INCITE_name_given_code[408] = "bm_theta"
INCITE_code_given_name["bm_theta"] = 408
INCITE_tex_given_code[408] = ""

INCITE_name_given_code[409] = "bm_phi"
INCITE_code_given_name["bm_phi"] = 409
INCITE_tex_given_code[409] = ""

INCITE_name_given_code[410] = "db_r_dr"
INCITE_code_given_name["db_r_dr"] = 410
INCITE_tex_given_code[410] = "full"

INCITE_name_given_code[411] = "db_theta_dr"
INCITE_code_given_name["db_theta_dr"] = 411
INCITE_tex_given_code[411] = ""

INCITE_name_given_code[412] = "db_phi_dr"
INCITE_code_given_name["db_phi_dr"] = 412
INCITE_tex_given_code[412] = ""

INCITE_name_given_code[413] = "dbp_r_dr"
INCITE_code_given_name["dbp_r_dr"] = 413
INCITE_tex_given_code[413] = "fluctuating"

INCITE_name_given_code[414] = "dbp_theta_dr"
INCITE_code_given_name["dbp_theta_dr"] = 414
INCITE_tex_given_code[414] = ""

INCITE_name_given_code[415] = "dbp_phi_dr"
INCITE_code_given_name["dbp_phi_dr"] = 415
INCITE_tex_given_code[415] = ""

INCITE_name_given_code[416] = "dbm_r_dr"
INCITE_code_given_name["dbm_r_dr"] = 416
INCITE_tex_given_code[416] = "mean"

INCITE_name_given_code[417] = "dbm_theta_dr"
INCITE_code_given_name["dbm_theta_dr"] = 417
INCITE_tex_given_code[417] = ""

INCITE_name_given_code[418] = "dbm_phi_dr"
INCITE_code_given_name["dbm_phi_dr"] = 418
INCITE_tex_given_code[418] = ""

INCITE_name_given_code[419] = "db_r_dt"
INCITE_code_given_name["db_r_dt"] = 419
INCITE_tex_given_code[419] = "full"

INCITE_name_given_code[420] = "db_theta_dt"
INCITE_code_given_name["db_theta_dt"] = 420
INCITE_tex_given_code[420] = ""

INCITE_name_given_code[421] = "db_phi_dt"
INCITE_code_given_name["db_phi_dt"] = 421
INCITE_tex_given_code[421] = ""

INCITE_name_given_code[422] = "dbp_r_dt"
INCITE_code_given_name["dbp_r_dt"] = 422
INCITE_tex_given_code[422] = "fluctuating"

INCITE_name_given_code[423] = "dbp_theta_dt"
INCITE_code_given_name["dbp_theta_dt"] = 423
INCITE_tex_given_code[423] = ""

INCITE_name_given_code[424] = "dbp_phi_dt"
INCITE_code_given_name["dbp_phi_dt"] = 424
INCITE_tex_given_code[424] = ""

INCITE_name_given_code[425] = "dbm_r_dt"
INCITE_code_given_name["dbm_r_dt"] = 425
INCITE_tex_given_code[425] = "mean"

INCITE_name_given_code[426] = "dbm_theta_dt"
INCITE_code_given_name["dbm_theta_dt"] = 426
INCITE_tex_given_code[426] = ""

INCITE_name_given_code[427] = "dbm_phi_dt"
INCITE_code_given_name["dbm_phi_dt"] = 427
INCITE_tex_given_code[427] = ""

INCITE_name_given_code[428] = "db_r_dp"
INCITE_code_given_name["db_r_dp"] = 428
INCITE_tex_given_code[428] = "full"

INCITE_name_given_code[429] = "db_theta_dp"
INCITE_code_given_name["db_theta_dp"] = 429
INCITE_tex_given_code[429] = ""

INCITE_name_given_code[430] = "db_phi_dp"
INCITE_code_given_name["db_phi_dp"] = 430
INCITE_tex_given_code[430] = ""

INCITE_name_given_code[431] = "dbp_r_dp"
INCITE_code_given_name["dbp_r_dp"] = 431
INCITE_tex_given_code[431] = "fluctuating"

INCITE_name_given_code[432] = "dbp_theta_dp"
INCITE_code_given_name["dbp_theta_dp"] = 432
INCITE_tex_given_code[432] = "(same as full if"

INCITE_name_given_code[433] = "dbp_phi_dp"
INCITE_code_given_name["dbp_phi_dp"] = 433
INCITE_tex_given_code[433] = "mean is azimuthal)"

INCITE_name_given_code[434] = "dbm_r_dp"
INCITE_code_given_name["dbm_r_dp"] = 434
INCITE_tex_given_code[434] = "mean"

INCITE_name_given_code[435] = "dbm_theta_dp"
INCITE_code_given_name["dbm_theta_dp"] = 435
INCITE_tex_given_code[435] = "(nonzero only when mean is"

INCITE_name_given_code[436] = "dbm_phi_dp"
INCITE_code_given_name["dbm_phi_dp"] = 436
INCITE_tex_given_code[436] = "spherical, not azimuthal)"

INCITE_name_given_code[437] = "db_r_dtr"
INCITE_code_given_name["db_r_dtr"] = 437
INCITE_tex_given_code[437] = "full"

INCITE_name_given_code[438] = "db_theta_dtr"
INCITE_code_given_name["db_theta_dtr"] = 438
INCITE_tex_given_code[438] = ""

INCITE_name_given_code[439] = "db_phi_dtr"
INCITE_code_given_name["db_phi_dtr"] = 439
INCITE_tex_given_code[439] = ""

INCITE_name_given_code[440] = "dbp_r_dtr"
INCITE_code_given_name["dbp_r_dtr"] = 440
INCITE_tex_given_code[440] = "fluctuating"

INCITE_name_given_code[441] = "dbp_theta_dtr"
INCITE_code_given_name["dbp_theta_dtr"] = 441
INCITE_tex_given_code[441] = ""

INCITE_name_given_code[442] = "dbp_phi_dtr"
INCITE_code_given_name["dbp_phi_dtr"] = 442
INCITE_tex_given_code[442] = ""

INCITE_name_given_code[443] = "dbm_r_dtr"
INCITE_code_given_name["dbm_r_dtr"] = 443
INCITE_tex_given_code[443] = "mean"

INCITE_name_given_code[444] = "dbm_theta_dtr"
INCITE_code_given_name["dbm_theta_dtr"] = 444
INCITE_tex_given_code[444] = ""

INCITE_name_given_code[445] = "dbm_phi_dtr"
INCITE_code_given_name["dbm_phi_dtr"] = 445
INCITE_tex_given_code[445] = ""

INCITE_name_given_code[446] = "db_r_dprs"
INCITE_code_given_name["db_r_dprs"] = 446
INCITE_tex_given_code[446] = "full"

INCITE_name_given_code[447] = "db_theta_dprs"
INCITE_code_given_name["db_theta_dprs"] = 447
INCITE_tex_given_code[447] = ""

INCITE_name_given_code[448] = "db_phi_dprs"
INCITE_code_given_name["db_phi_dprs"] = 448
INCITE_tex_given_code[448] = ""

INCITE_name_given_code[449] = "dbp_r_dprs"
INCITE_code_given_name["dbp_r_dprs"] = 449
INCITE_tex_given_code[449] = "fluctuating"

INCITE_name_given_code[450] = "dbp_theta_dprs"
INCITE_code_given_name["dbp_theta_dprs"] = 450
INCITE_tex_given_code[450] = ""

INCITE_name_given_code[451] = "dbp_phi_dprs"
INCITE_code_given_name["dbp_phi_dprs"] = 451
INCITE_tex_given_code[451] = ""

INCITE_name_given_code[452] = "dbm_r_dprs"
INCITE_code_given_name["dbm_r_dprs"] = 452
INCITE_tex_given_code[452] = "mean"

INCITE_name_given_code[453] = "dbm_theta_dprs"
INCITE_code_given_name["dbm_theta_dprs"] = 453
INCITE_tex_given_code[453] = ""

INCITE_name_given_code[454] = "dbm_phi_dprs"
INCITE_code_given_name["dbm_phi_dprs"] = 454
INCITE_tex_given_code[454] = ""

INCITE_name_given_code[455] = "j_r"
INCITE_code_given_name["j_r"] = 455
INCITE_tex_given_code[455] = "radial current density"

INCITE_name_given_code[456] = "jp_r"
INCITE_code_given_name["jp_r"] = 456
INCITE_tex_given_code[456] = ""

INCITE_name_given_code[457] = "jm_r"
INCITE_code_given_name["jm_r"] = 457
INCITE_tex_given_code[457] = ""

INCITE_name_given_code[458] = "j_theta"
INCITE_code_given_name["j_theta"] = 458
INCITE_tex_given_code[458] = "theta current density"

INCITE_name_given_code[459] = "jp_theta"
INCITE_code_given_name["jp_theta"] = 459
INCITE_tex_given_code[459] = ""

INCITE_name_given_code[460] = "jm_theta"
INCITE_code_given_name["jm_theta"] = 460
INCITE_tex_given_code[460] = ""

INCITE_name_given_code[461] = "j_phi"
INCITE_code_given_name["j_phi"] = 461
INCITE_tex_given_code[461] = "phi current density"

INCITE_name_given_code[462] = "jp_phi"
INCITE_code_given_name["jp_phi"] = 462
INCITE_tex_given_code[462] = ""

INCITE_name_given_code[463] = "jm_phi"
INCITE_code_given_name["jm_phi"] = 463
INCITE_tex_given_code[463] = ""

INCITE_name_given_code[464] = "j_r_sq"
INCITE_code_given_name["j_r_sq"] = 464
INCITE_tex_given_code[464] = "(j_r)^2"

INCITE_name_given_code[465] = "jp_r_sq"
INCITE_code_given_name["jp_r_sq"] = 465
INCITE_tex_given_code[465] = "(jp_r)^2"

INCITE_name_given_code[466] = "j_theta_sq"
INCITE_code_given_name["j_theta_sq"] = 466
INCITE_tex_given_code[466] = "(j_theta)^2"

INCITE_name_given_code[467] = "jp_theta_sq"
INCITE_code_given_name["jp_theta_sq"] = 467
INCITE_tex_given_code[467] = "(jp_theta)^2"

INCITE_name_given_code[468] = "j_phi_sq"
INCITE_code_given_name["j_phi_sq"] = 468
INCITE_tex_given_code[468] = "(j_theta)^2"

INCITE_name_given_code[469] = "jp_phi_sq"
INCITE_code_given_name["jp_phi_sq"] = 469
INCITE_tex_given_code[469] = "(jp_theta)^2"

INCITE_name_given_code[470] = "j_sq"
INCITE_code_given_name["j_sq"] = 470
INCITE_tex_given_code[470] = "j dot j"

INCITE_name_given_code[471] = "jp_sq"
INCITE_code_given_name["jp_sq"] = 471
INCITE_tex_given_code[471] = "j' dot j'"

INCITE_name_given_code[472] = "ohmic_heat"
INCITE_code_given_name["ohmic_heat"] = 472
INCITE_tex_given_code[472] = "eta{  j  dot  j}"

INCITE_name_given_code[473] = "ohmic_heat_pp"
INCITE_code_given_name["ohmic_heat_pp"] = 473
INCITE_tex_given_code[473] = "eta{  j' dot  j'}"

INCITE_name_given_code[474] = "ohmic_heat_mm"
INCITE_code_given_name["ohmic_heat_mm"] = 474
INCITE_tex_given_code[474] = "eta{ <j> dot <j>}"

INCITE_name_given_code[475] = "magnetic_energy"
INCITE_code_given_name["magnetic_energy"] = 475
INCITE_tex_given_code[475] = "b^2"

INCITE_name_given_code[476] = "radial_me"
INCITE_code_given_name["radial_me"] = 476
INCITE_tex_given_code[476] = "{b_r}^2"

INCITE_name_given_code[477] = "theta_me"
INCITE_code_given_name["theta_me"] = 477
INCITE_tex_given_code[477] = "{b_theta}^2"

INCITE_name_given_code[478] = "phi_me"
INCITE_code_given_name["phi_me"] = 478
INCITE_tex_given_code[478] = "{b_phi}^2"

INCITE_name_given_code[479] = "mmagnetic_energy"
INCITE_code_given_name["mmagnetic_energy"] = 479
INCITE_tex_given_code[479] = "<b>^2"

INCITE_name_given_code[480] = "radial_mme"
INCITE_code_given_name["radial_mme"] = 480
INCITE_tex_given_code[480] = "<b_r>^2"

INCITE_name_given_code[481] = "theta_mme"
INCITE_code_given_name["theta_mme"] = 481
INCITE_tex_given_code[481] = "<b_theta>^2"

INCITE_name_given_code[482] = "phi_mme"
INCITE_code_given_name["phi_mme"] = 482
INCITE_tex_given_code[482] = "<b_phi>^2"

INCITE_name_given_code[483] = "pmagnetic_energy"
INCITE_code_given_name["pmagnetic_energy"] = 483
INCITE_tex_given_code[483] = "{b'}^2"

INCITE_name_given_code[484] = "radial_pme"
INCITE_code_given_name["radial_pme"] = 484
INCITE_tex_given_code[484] = "{b_r'}^2"

INCITE_name_given_code[485] = "theta_pme"
INCITE_code_given_name["theta_pme"] = 485
INCITE_tex_given_code[485] = "{b_theta'}^2"

INCITE_name_given_code[486] = "phi_pme"
INCITE_code_given_name["phi_pme"] = 486
INCITE_tex_given_code[486] = "{b_phi'}^2"

INCITE_name_given_code[487] = "j_cross_b_r"
INCITE_code_given_name["j_cross_b_r"] = 487
INCITE_tex_given_code[487] = "radial component of j x b"

INCITE_name_given_code[488] = "j_cross_b_theta"
INCITE_code_given_name["j_cross_b_theta"] = 488
INCITE_tex_given_code[488] = "theta component of j x b"

INCITE_name_given_code[489] = "j_cross_b_phi"
INCITE_code_given_name["j_cross_b_phi"] = 489
INCITE_tex_given_code[489] = "phi component of j x b"

INCITE_name_given_code[490] = "jp_cross_bm_r"
INCITE_code_given_name["jp_cross_bm_r"] = 490
INCITE_tex_given_code[490] = "radial component of j' x <b>"

INCITE_name_given_code[491] = "jp_cross_bm_theta"
INCITE_code_given_name["jp_cross_bm_theta"] = 491
INCITE_tex_given_code[491] = "theta component of j' x <b>"

INCITE_name_given_code[492] = "jp_cross_bm_phi"
INCITE_code_given_name["jp_cross_bm_phi"] = 492
INCITE_tex_given_code[492] = "phi component of j' x <b>"

INCITE_name_given_code[493] = "jm_cross_bp_r"
INCITE_code_given_name["jm_cross_bp_r"] = 493
INCITE_tex_given_code[493] = "radial component of <j> x b'"

INCITE_name_given_code[494] = "jm_cross_bp_theta"
INCITE_code_given_name["jm_cross_bp_theta"] = 494
INCITE_tex_given_code[494] = "theta component of <j> x b'"

INCITE_name_given_code[495] = "jm_cross_bp_phi"
INCITE_code_given_name["jm_cross_bp_phi"] = 495
INCITE_tex_given_code[495] = "phi component of <j> x b'"

INCITE_name_given_code[496] = "jm_cross_bm_r"
INCITE_code_given_name["jm_cross_bm_r"] = 496
INCITE_tex_given_code[496] = "radial component of <j> x <b>"

INCITE_name_given_code[497] = "jm_cross_bm_theta"
INCITE_code_given_name["jm_cross_bm_theta"] = 497
INCITE_tex_given_code[497] = "theta component of <j> x <b>"

INCITE_name_given_code[498] = "jm_cross_bm_phi"
INCITE_code_given_name["jm_cross_bm_phi"] = 498
INCITE_tex_given_code[498] = "phi component of <j> x <b>"

INCITE_name_given_code[499] = "jp_cross_bp_r"
INCITE_code_given_name["jp_cross_bp_r"] = 499
INCITE_tex_given_code[499] = "radial component of j' x b'"

INCITE_name_given_code[500] = "jp_cross_bp_theta"
INCITE_code_given_name["jp_cross_bp_theta"] = 500
INCITE_tex_given_code[500] = "theta component of j' x b'"

INCITE_name_given_code[501] = "jp_cross_bp_phi"
INCITE_code_given_name["jp_cross_bp_phi"] = 501
INCITE_tex_given_code[501] = "phi component of j' x b'"

INCITE_name_given_code[502] = "maxwell_stress_r"
INCITE_code_given_name["maxwell_stress_r"] = 502
INCITE_tex_given_code[502] = "-rsintheta {b_r'}{b_phi'}*lorentz_coeff"

INCITE_name_given_code[503] = "maxwell_stress_theta"
INCITE_code_given_name["maxwell_stress_theta"] = 503
INCITE_tex_given_code[503] = "-rsintheta {b_theta'}{b_phi'}*lorentz_coeff"

INCITE_name_given_code[504] = "magnetic_torque_r"
INCITE_code_given_name["magnetic_torque_r"] = 504
INCITE_tex_given_code[504] = "-rsintheta <b_r><b_phi>*lorentz_coeff"

INCITE_name_given_code[505] = "magnetic_torque_theta"
INCITE_code_given_name["magnetic_torque_theta"] = 505
INCITE_tex_given_code[505] = "-rsintheta <b_theta><b_phi>*lorentz_coeff"

INCITE_name_given_code[506] = "induction_shear_r"
INCITE_code_given_name["induction_shear_r"] = 506
INCITE_tex_given_code[506] = "radial component of {b dot grad v}"

INCITE_name_given_code[507] = "induction_comp_r"
INCITE_code_given_name["induction_comp_r"] = 507
INCITE_tex_given_code[507] = "radial component of -{div dot v}b"

INCITE_name_given_code[508] = "induction_advec_r"
INCITE_code_given_name["induction_advec_r"] = 508
INCITE_tex_given_code[508] = "radial component of -{v dot grad b}"

INCITE_name_given_code[509] = "induction_r"
INCITE_code_given_name["induction_r"] = 509
INCITE_tex_given_code[509] = "radial component of del cros {v x b}"

INCITE_name_given_code[510] = "induction_diff_r"
INCITE_code_given_name["induction_diff_r"] = 510
INCITE_tex_given_code[510] = "radial component of -del x (eta {del x b})"

INCITE_name_given_code[511] = "induction_shear_theta"
INCITE_code_given_name["induction_shear_theta"] = 511
INCITE_tex_given_code[511] = "theta component of {b dot grad v}"

INCITE_name_given_code[512] = "induction_comp_theta"
INCITE_code_given_name["induction_comp_theta"] = 512
INCITE_tex_given_code[512] = "theta component of -{div dot v}b"

INCITE_name_given_code[513] = "induction_advec_theta"
INCITE_code_given_name["induction_advec_theta"] = 513
INCITE_tex_given_code[513] = "theta component of -{v dot grad b}"

INCITE_name_given_code[514] = "induction_theta"
INCITE_code_given_name["induction_theta"] = 514
INCITE_tex_given_code[514] = "theta component of del cros {v x b}"

INCITE_name_given_code[515] = "induction_diff_theta"
INCITE_code_given_name["induction_diff_theta"] = 515
INCITE_tex_given_code[515] = "theta component of -del x (eta {del x b})"

INCITE_name_given_code[516] = "induction_shear_phi"
INCITE_code_given_name["induction_shear_phi"] = 516
INCITE_tex_given_code[516] = "phi component of {b dot grad v}"

INCITE_name_given_code[517] = "induction_comp_phi"
INCITE_code_given_name["induction_comp_phi"] = 517
INCITE_tex_given_code[517] = "phi component of -{div dot v}b"

INCITE_name_given_code[518] = "induction_advec_phi"
INCITE_code_given_name["induction_advec_phi"] = 518
INCITE_tex_given_code[518] = "phi component of -{v dot grad b}"

INCITE_name_given_code[519] = "induction_phi"
INCITE_code_given_name["induction_phi"] = 519
INCITE_tex_given_code[519] = "phi component of del cros {v x b}"

INCITE_name_given_code[520] = "induction_diff_phi"
INCITE_code_given_name["induction_diff_phi"] = 520
INCITE_tex_given_code[520] = "phi component of -del x (eta {del x b})"

INCITE_name_given_code[521] = "induction_shear_vmbm_r"
INCITE_code_given_name["induction_shear_vmbm_r"] = 521
INCITE_tex_given_code[521] = "radial component of {<b> dot grad <v>}"

INCITE_name_given_code[522] = "induction_comp_vmbm_r"
INCITE_code_given_name["induction_comp_vmbm_r"] = 522
INCITE_tex_given_code[522] = "radial component of -{div dot <v>}<b>"

INCITE_name_given_code[523] = "induction_advec_vmbm_r"
INCITE_code_given_name["induction_advec_vmbm_r"] = 523
INCITE_tex_given_code[523] = "radial component of -{<v> dot grad <b>}"

INCITE_name_given_code[524] = "induction_vmbm_r"
INCITE_code_given_name["induction_vmbm_r"] = 524
INCITE_tex_given_code[524] = "radial component of del cros {<v> x <b>}"

INCITE_name_given_code[525] = "induction_diff_bm_r"
INCITE_code_given_name["induction_diff_bm_r"] = 525
INCITE_tex_given_code[525] = "radial component of -del x (eta {del x <b>})"

INCITE_name_given_code[526] = "induction_shear_vmbm_theta"
INCITE_code_given_name["induction_shear_vmbm_theta"] = 526
INCITE_tex_given_code[526] = "theta component of {<b> dot grad <v>}"

INCITE_name_given_code[527] = "induction_comp_vmbm_theta"
INCITE_code_given_name["induction_comp_vmbm_theta"] = 527
INCITE_tex_given_code[527] = "theta component of -{div dot <v>}<b>"

INCITE_name_given_code[528] = "induction_advec_vmbm_theta"
INCITE_code_given_name["induction_advec_vmbm_theta"] = 528
INCITE_tex_given_code[528] = "theta component of -{<v> dot grad <b>}"

INCITE_name_given_code[529] = "induction_vmbm_theta"
INCITE_code_given_name["induction_vmbm_theta"] = 529
INCITE_tex_given_code[529] = "theta component of del cros {<v> x <b>}"

INCITE_name_given_code[530] = "induction_diff_bm_theta"
INCITE_code_given_name["induction_diff_bm_theta"] = 530
INCITE_tex_given_code[530] = "theta component of -del x (eta {del x <b>})"

INCITE_name_given_code[531] = "induction_shear_vmbm_phi"
INCITE_code_given_name["induction_shear_vmbm_phi"] = 531
INCITE_tex_given_code[531] = "phi component of {<b> dot grad <v>}"

INCITE_name_given_code[532] = "induction_comp_vmbm_phi"
INCITE_code_given_name["induction_comp_vmbm_phi"] = 532
INCITE_tex_given_code[532] = "phi component of -{div dot <v>}<b>"

INCITE_name_given_code[533] = "induction_advec_vmbm_phi"
INCITE_code_given_name["induction_advec_vmbm_phi"] = 533
INCITE_tex_given_code[533] = "phi component of -{<v> dot grad <b>}"

INCITE_name_given_code[534] = "induction_vmbm_phi"
INCITE_code_given_name["induction_vmbm_phi"] = 534
INCITE_tex_given_code[534] = "phi component of del cros {<v> x <b>}"

INCITE_name_given_code[535] = "induction_diff_bm_phi"
INCITE_code_given_name["induction_diff_bm_phi"] = 535
INCITE_tex_given_code[535] = "phi component of -del x (eta {del x <b>})"

INCITE_name_given_code[536] = "induction_shear_vmbp_r"
INCITE_code_given_name["induction_shear_vmbp_r"] = 536
INCITE_tex_given_code[536] = "radial component of {b' dot grad <v>}"

INCITE_name_given_code[537] = "induction_comp_vmbp_r"
INCITE_code_given_name["induction_comp_vmbp_r"] = 537
INCITE_tex_given_code[537] = "radial component of -{div dot <v>}b'"

INCITE_name_given_code[538] = "induction_advec_vmbp_r"
INCITE_code_given_name["induction_advec_vmbp_r"] = 538
INCITE_tex_given_code[538] = "radial component of -{<v> dot grad b'}"

INCITE_name_given_code[539] = "induction_vmbp_r"
INCITE_code_given_name["induction_vmbp_r"] = 539
INCITE_tex_given_code[539] = "radial component of del cros {<v> x b'}"

INCITE_name_given_code[540] = "induction_diff_bp_r"
INCITE_code_given_name["induction_diff_bp_r"] = 540
INCITE_tex_given_code[540] = "radial component of -del x (eta {del x b'})"

INCITE_name_given_code[541] = "induction_shear_vmbp_theta"
INCITE_code_given_name["induction_shear_vmbp_theta"] = 541
INCITE_tex_given_code[541] = "theta component of {b' dot grad <v>}"

INCITE_name_given_code[542] = "induction_comp_vmbp_theta"
INCITE_code_given_name["induction_comp_vmbp_theta"] = 542
INCITE_tex_given_code[542] = "theta component of -{div dot <v>}b'"

INCITE_name_given_code[543] = "induction_advec_vmbp_theta"
INCITE_code_given_name["induction_advec_vmbp_theta"] = 543
INCITE_tex_given_code[543] = "theta component of -{<v> dot grad b'}"

INCITE_name_given_code[544] = "induction_vmbp_theta"
INCITE_code_given_name["induction_vmbp_theta"] = 544
INCITE_tex_given_code[544] = "theta component of del cros {<v> x b'}"

INCITE_name_given_code[545] = "induction_diff_bp_theta"
INCITE_code_given_name["induction_diff_bp_theta"] = 545
INCITE_tex_given_code[545] = "theta component of -del x (eta {del x b'})"

INCITE_name_given_code[546] = "induction_shear_vmbp_phi"
INCITE_code_given_name["induction_shear_vmbp_phi"] = 546
INCITE_tex_given_code[546] = "phi component of {b' dot grad <v>}"

INCITE_name_given_code[547] = "induction_comp_vmbp_phi"
INCITE_code_given_name["induction_comp_vmbp_phi"] = 547
INCITE_tex_given_code[547] = "phi component of -{div dot <v>}b'"

INCITE_name_given_code[548] = "induction_advec_vmbp_phi"
INCITE_code_given_name["induction_advec_vmbp_phi"] = 548
INCITE_tex_given_code[548] = "phi component of -{<v> dot grad b'}"

INCITE_name_given_code[549] = "induction_vmbp_phi"
INCITE_code_given_name["induction_vmbp_phi"] = 549
INCITE_tex_given_code[549] = "phi component of del cros {<v> x b'}"

INCITE_name_given_code[550] = "induction_diff_bp_phi"
INCITE_code_given_name["induction_diff_bp_phi"] = 550
INCITE_tex_given_code[550] = "phi component of -del x (eta {del x b'})"

INCITE_name_given_code[551] = "induction_shear_vpbm_r"
INCITE_code_given_name["induction_shear_vpbm_r"] = 551
INCITE_tex_given_code[551] = "radial component of {<b> dot grad v'}"

INCITE_name_given_code[552] = "induction_comp_vpbm_r"
INCITE_code_given_name["induction_comp_vpbm_r"] = 552
INCITE_tex_given_code[552] = "radial component of -{div dot v'}<b>"

INCITE_name_given_code[553] = "induction_advec_vpbm_r"
INCITE_code_given_name["induction_advec_vpbm_r"] = 553
INCITE_tex_given_code[553] = "radial component of -{v' dot grad <b>}"

INCITE_name_given_code[554] = "induction_vpbm_r"
INCITE_code_given_name["induction_vpbm_r"] = 554
INCITE_tex_given_code[554] = "radial component of del cros {v' x <b>}"

INCITE_name_given_code[555] = "induction_shear_vpbm_theta"
INCITE_code_given_name["induction_shear_vpbm_theta"] = 555
INCITE_tex_given_code[555] = "theta component of {<b> dot grad v'}"

INCITE_name_given_code[556] = "induction_comp_vpbm_theta"
INCITE_code_given_name["induction_comp_vpbm_theta"] = 556
INCITE_tex_given_code[556] = "theta component of -{div dot v'}<b>"

INCITE_name_given_code[557] = "induction_advec_vpbm_theta"
INCITE_code_given_name["induction_advec_vpbm_theta"] = 557
INCITE_tex_given_code[557] = "theta component of -{v' dot grad <b>}"

INCITE_name_given_code[558] = "induction_vpbm_theta"
INCITE_code_given_name["induction_vpbm_theta"] = 558
INCITE_tex_given_code[558] = "theta component of del cros {v' x <b>}"

INCITE_name_given_code[559] = "induction_shear_vpbm_phi"
INCITE_code_given_name["induction_shear_vpbm_phi"] = 559
INCITE_tex_given_code[559] = "phi component of {<b> dot grad v'}"

INCITE_name_given_code[560] = "induction_comp_vpbm_phi"
INCITE_code_given_name["induction_comp_vpbm_phi"] = 560
INCITE_tex_given_code[560] = "phi component of -{div dot v'}<b>"

INCITE_name_given_code[561] = "induction_advec_vpbm_phi"
INCITE_code_given_name["induction_advec_vpbm_phi"] = 561
INCITE_tex_given_code[561] = "phi component of -{v' dot grad <b>}"

INCITE_name_given_code[562] = "induction_vpbm_phi"
INCITE_code_given_name["induction_vpbm_phi"] = 562
INCITE_tex_given_code[562] = "phi component of del cros {v' x <b>}"

INCITE_name_given_code[563] = "induction_shear_vpbp_r"
INCITE_code_given_name["induction_shear_vpbp_r"] = 563
INCITE_tex_given_code[563] = "radial component of {b' dot grad v'}"

INCITE_name_given_code[564] = "induction_comp_vpbp_r"
INCITE_code_given_name["induction_comp_vpbp_r"] = 564
INCITE_tex_given_code[564] = "radial component of -{div dot v'}b'"

INCITE_name_given_code[565] = "induction_advec_vpbp_r"
INCITE_code_given_name["induction_advec_vpbp_r"] = 565
INCITE_tex_given_code[565] = "radial component of -{v' dot grad b'}"

INCITE_name_given_code[566] = "induction_vpbp_r"
INCITE_code_given_name["induction_vpbp_r"] = 566
INCITE_tex_given_code[566] = "radial component of del cros {v' x b'}"

INCITE_name_given_code[567] = "induction_shear_vpbp_theta"
INCITE_code_given_name["induction_shear_vpbp_theta"] = 567
INCITE_tex_given_code[567] = "theta component of {b' dot grad v'}"

INCITE_name_given_code[568] = "induction_comp_vpbp_theta"
INCITE_code_given_name["induction_comp_vpbp_theta"] = 568
INCITE_tex_given_code[568] = "theta component of -{div dot v'}b'"

INCITE_name_given_code[569] = "induction_advec_vpbp_theta"
INCITE_code_given_name["induction_advec_vpbp_theta"] = 569
INCITE_tex_given_code[569] = "theta component of -{v' dot grad b'}"

INCITE_name_given_code[570] = "induction_vpbp_theta"
INCITE_code_given_name["induction_vpbp_theta"] = 570
INCITE_tex_given_code[570] = "theta component of del cros {v' x b'}"

INCITE_name_given_code[571] = "induction_shear_vpbp_phi"
INCITE_code_given_name["induction_shear_vpbp_phi"] = 571
INCITE_tex_given_code[571] = "phi component of {b' dot grad v'}"

INCITE_name_given_code[572] = "induction_comp_vpbp_phi"
INCITE_code_given_name["induction_comp_vpbp_phi"] = 572
INCITE_tex_given_code[572] = "phi component of -{div dot v'}b'"

INCITE_name_given_code[573] = "induction_advec_vpbp_phi"
INCITE_code_given_name["induction_advec_vpbp_phi"] = 573
INCITE_tex_given_code[573] = "phi component of -{v' dot grad b'}"

INCITE_name_given_code[574] = "induction_vpbp_phi"
INCITE_code_given_name["induction_vpbp_phi"] = 574
INCITE_tex_given_code[574] = "phi component of del cros {v' x b'}"

INCITE_name_given_code[701] = "cross_helicity"
INCITE_code_given_name["cross_helicity"] = 701
INCITE_tex_given_code[701] = "v dot b"

INCITE_name_given_code[702] = "turb_cross_helicity"
INCITE_code_given_name["turb_cross_helicity"] = 702
INCITE_tex_given_code[702] = ""


